dist: bionic
addons:
  apt:
    packages:
      - lftp
      - bgpdump
      - tree
language: rust
cache:
  cargo: true
  directories:
    - /home/travis/gopath/bin/
env:
  global:
  - BGPTOOLS_VERSION=0.0.3
install:
  - export PATH=$PATH:$HOME/go/bin
  - ./dependency.sh
script:
  - ./generate.sh
  - ./stat.sh
deploy:
  provider: script
  script: ./upload.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE == cron
